### ISSUE TITLE
Less than ideal...  

### ISSUE THREAD

**Issue by Voluntary-zcash** [calibrae-project/calibrd#3]
I can't keep up with changing email, chat, forums - so here I am.  Where should I be looking for the right links?

**Comment by l0k18** [comment]
I changed them to simple url's that you can remember:

http://forum.calibr.ae
http://gitlab.calibr.ae
http://chat.calibr.ae

The chat is the central nerve center, so you really should be hanging out there if you want to follow or join in business... 

gitlab has a better interface and the source of the web application is open source (you can't run your own github but you can run a gitlab server, we may want to do that in the future, in fact it might be how I implement the 'write-code-for-rewards' system, with their code)

You know the forum already. all of these are just handy URL redirections from the DNS registrar.

Part of the reason why I have abandoned google hangouts is, aside from it being a really shit chat interface, someone compromised my google mail account and made a reply to an email that I sent to myself, as though to intimidate me. So I am now redirecting my gmail to my mail.com address as well. I am quite sure I know which individual hacked my google account session so I spent about 6 hours going through all my saved accounts, copying them out, deleting them from my google account, and then set up a password manager which allows me to easily manage to have 32 character passwords, each different for each account. The troll in question has been a bit like the stick that has got me working harder on this project. Thus also, this repository will now languish.
